spring:
  application:
    name: assignment
  datasource:
    url: jdbc:h2:mem:assignment
    username: root
    password: root
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true